<a href="https://colab.research.google.com/github/Amitprataprana/Coursera/blob/master/KrishNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
my_list = [1,2,3,4,5,6]

arr = np.array(my_list)

In [5]:
type(arr)

numpy.ndarray

In [8]:
print(arr)
arr

[1 2 3 4 5 6]


array([1, 2, 3, 4, 5, 6])

In [6]:
arr.shape

(6,)

#Two dimensional Array

In [9]:
my_list1 =[1,2,3,4,5]
my_list2 =[2,3,4,5,6]
my_list3 =[3,4,5,6,7]

In [11]:
arr = np.array([my_list1,my_list2,my_list3])
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [19]:
arr.shape
arr = arr.reshape(5,3)
print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 2]
 [3 4 5]
 [6 3 4]
 [5 6 7]]
(5, 3)


#Indexing



In [25]:
arr[3]

array([6, 3, 4])

In [27]:
arr[:3,:2]

array([[1, 2],
       [4, 5],
       [3, 4]])

In [35]:
arr[:,1]

array([2, 5, 4, 3, 6])

#Inbuilt functions

In [37]:
arr = np.arange(0,10,2)
arr

array([0, 2, 4, 6, 8])

Linsapce gives the desired number of random values between some given range
eg:here between 1 to 20 , 50 values are required and linspace gives the following output.

In [39]:
np.linspace(1,20,50)

array([ 1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041,
        2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592,
        4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143,
        6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36734694,
        8.75510204,  9.14285714,  9.53061224,  9.91836735, 10.30612245,
       10.69387755, 11.08163265, 11.46938776, 11.85714286, 12.24489796,
       12.63265306, 13.02040816, 13.40816327, 13.79591837, 14.18367347,
       14.57142857, 14.95918367, 15.34693878, 15.73469388, 16.12244898,
       16.51020408, 16.89795918, 17.28571429, 17.67346939, 18.06122449,
       18.44897959, 18.83673469, 19.2244898 , 19.6122449 , 20.        ])

In [47]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [48]:
arr1 = arr
arr1[3:]=100
print(arr1)
print(arr)

[  1   2   3 100 100 100 100 100 100]
[  1   2   3 100 100 100 100 100 100]


By assigning the other name to array change in any one of the arrays will appear in both the arrays.
Thus to avoid this scenario copy funtion is used

In [49]:
arr1 = arr.copy()
arr1[4:] = 500
print(arr1)
print(arr)

[  1   2   3 100 500 500 500 500 500]
[  1   2   3 100 100 100 100 100 100]


In [57]:
## Some conditions are very useful in Explanatory Data Analysis

val = 2
print(arr[arr <val])
print(arr*2)
print(arr<2)


[1]
[  2   4   6 200 200 200 200 200 200]
[ True False False False False False False False False]


In [60]:
np.ones((4,5),dtype =int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [61]:
np.random.rand(3,3)

array([[0.26412339, 0.04344305, 0.16461518],
       [0.71504301, 0.53608925, 0.66749296],
       [0.96490197, 0.21559385, 0.01829173]])

In [62]:
np.random.randint(1,4,(3,3))

array([[1, 2, 1],
       [3, 2, 1],
       [2, 3, 2]])

In [63]:
np.random.randn(1,20)

array([[-0.91660803,  0.47898688,  0.99549086, -0.12164416,  1.92903298,
        -0.78610831, -0.87043568,  0.18486645,  0.05823606, -0.52125157,
        -1.08182112, -0.87408152,  0.01071095, -1.05463279,  1.36967371,
        -0.48237684,  0.89342555,  2.71076462,  0.43750745,  0.74257229]])

In [64]:
np.random.randint(0,800,45).reshape(9,5)

array([[425, 272,  30, 624, 627],
       [  7, 747, 322, 122, 260],
       [148, 188, 242, 425, 360],
       [637, 633, 258, 688, 620],
       [739, 267, 357, 383, 248],
       [478, 186,  81, 366, 351],
       [627, 570, 363, 480, 402],
       [285,  96, 154, 345, 786],
       [754, 147, 334, 726, 242]])